Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand",
            "name": "AnalyzeFilesCommand",
            "summary": "AnalyzeFilesCommand.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020AnalyzeFilesCommand.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003AexecuteCommand\u0028\u0029",
            "name": "executeCommand",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#method_executeCommand"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003AexportToJson\u0028\u0029",
            "name": "exportToJson",
            "summary": "Export\u0020analysis\u0020results\u0020to\u0020a\u0020JSON\u0020file.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#method_exportToJson"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A\u0024analysisService",
            "name": "analysisService",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#property_analysisService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand",
            "name": "DbBackupCommand",
            "summary": "DbBackupCommand.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand",
            "name": "DbRestoreCommand",
            "summary": "DbRestoreCommand.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003AnormalizePath\u0028\u0029",
            "name": "normalizePath",
            "summary": "Normalize\u0020a\u0020given\u0020path\u0020to\u0020its\u0020absolute\u0020form.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#method_normalizePath"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand",
            "name": "GenerateTestsCommand",
            "summary": "ExperimentalGenerateTestsCommand.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020ExperimentalGenerateTestsCommand.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AparseOneFile\u0028\u0029",
            "name": "parseOneFile",
            "summary": "Common\u0020logic\u0020to\u0020parse\u0020a\u0020single\u0020file\u0020with\u0020parser\/traverser\/visitor.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_parseOneFile"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AgetPhpFiles\u0028\u0029",
            "name": "getPhpFiles",
            "summary": "Recursively\u0020retrieve\u0020PHP\u0020files\u0020in\u0020a\u0020directory.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_getPhpFiles"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AnormalizePath\u0028\u0029",
            "name": "normalizePath",
            "summary": "Convert\u0020a\u0020relative\u0020path\u0020to\u0020absolute\u0020if\u0020necessary.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_normalizePath"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AisAbsolutePath\u0028\u0029",
            "name": "isAbsolutePath",
            "summary": "Determines\u0020if\u0020a\u0020given\u0020path\u0020is\u0020absolute.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_isAbsolutePath"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AgenerateTestClass\u0028\u0029",
            "name": "generateTestClass",
            "summary": "Generate\u0020or\u0020update\u0020a\u0020PHPUnit\u0020test\u0020class\u0020for\u0020the\u0020discovered\u0020class\u0020info.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_generateTestClass"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AcreateNewTestFile\u0028\u0029",
            "name": "createNewTestFile",
            "summary": "Creates\u0020a\u0020new\u0020PHPUnit\u0020test\u0020file\u0020with\u0020a\u0020basic\u0020template.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_createNewTestFile"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003AappendMissingMethods\u0028\u0029",
            "name": "appendMissingMethods",
            "summary": "Appends\u0020missing\u0020test\u0020methods\u0020to\u0020an\u0020existing\u0020test\u0020file.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#method_appendMissingMethods"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental\\GenerateTestsCommand\u003A\u003A\u0024parserService",
            "name": "parserService",
            "summary": "",
            "url": "classes/App-Console-Commands-Experimental-GenerateTestsCommand.html#property_parserService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand",
            "name": "FilesCommand",
            "summary": "FilesCommand.",
            "url": "classes/App-Console-Commands-FilesCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020incoming\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AexecuteCommand\u0028\u0029",
            "name": "executeCommand",
            "summary": "Execute\u0020the\u0020command\u0020logic.",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_executeCommand"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AgetOutputFile\u0028\u0029",
            "name": "getOutputFile",
            "summary": "Retrieve\u0020and\u0020normalize\u0020the\u0020output\u0020file\u0020path.",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_getOutputFile"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AgetClassLimit\u0028\u0029",
            "name": "getClassLimit",
            "summary": "Retrieve\u0020the\u0020class\u0020limit\u0020option.",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_getClassLimit"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AgetMethodLimit\u0028\u0029",
            "name": "getMethodLimit",
            "summary": "Retrieve\u0020the\u0020method\u0020limit\u0020option.",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_getMethodLimit"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-FilesCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-FilesCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand",
            "name": "ParseFilesCommand",
            "summary": "ParseFilesCommand.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020ParseFilesCommand.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020incoming\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003AexportJson\u0028\u0029",
            "name": "exportJson",
            "summary": "Export\u0020collected\u0020items\u0020to\u0020a\u0020JSON\u0020file.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method_exportJson"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003AdisplayTable\u0028\u0029",
            "name": "displayTable",
            "summary": "Display\u0020the\u0020collected\u0020items\u0020in\u0020a\u0020table\u0020format.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method_displayTable"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A\u0024parserService",
            "name": "parserService",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#property_parserService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand",
            "name": "PassesProcessCommand",
            "summary": "Class\u0020PassesProcessCommand",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A\u0024analysisService",
            "name": "analysisService",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#property_analysisService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob",
            "name": "ProcessAnalysisPassJob",
            "summary": "ProcessAnalysisPassJob.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020ProcessAnalysisPassJob.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A\u0024analysisService",
            "name": "analysisService",
            "summary": "",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#property_analysisService"
        },                {
            "fqsen": "\\App\\Facades\\OpenAI",
            "name": "OpenAI",
            "summary": "OpenAI\u0020Facade.",
            "url": "classes/App-Facades-OpenAI.html"
        },                {
            "fqsen": "\\App\\Facades\\OpenAI\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "",
            "url": "classes/App-Facades-OpenAI.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController",
            "name": "AnalysisController",
            "summary": "Analysis\u0020Controller.",
            "url": "classes/App-Http-Controllers-AnalysisController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020all\u0020CodeAnalysis\u0020records.",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Show\u0020details\u0020for\u0020a\u0020specific\u0020CodeAnalysis\u0020record.",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003Aanalyze\u0028\u0029",
            "name": "analyze",
            "summary": "Trigger\u0020the\u0020parsing\u0020and\u0020queued\u0020AI\u0020passes\u0020for\u0020a\u0020specified\u0020file\u0020or\u0020directory\u0020path.",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method_analyze"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003A\u0024codeAnalysisService",
            "name": "codeAnalysisService",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnalysisController.html#property_codeAnalysisService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "Base\u0020Controller.",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob",
            "name": "ProcessAnalysisPassJob",
            "summary": "Process\u0020Analysis\u0020Pass\u0020Job.",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#method___construct"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020job.",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#method_handle"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A\u0024codeAnalysisId",
            "name": "codeAnalysisId",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#property_codeAnalysisId"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A\u0024passName",
            "name": "passName",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#property_passName"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A\u0024dryRun",
            "name": "dryRun",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#property_dryRun"
        },                {
            "fqsen": "\\App\\Models\\AIResult",
            "name": "AIResult",
            "summary": "AI\u0020Result\u0020Model.",
            "url": "classes/App-Models-AIResult.html"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003AcodeAnalysis\u0028\u0029",
            "name": "codeAnalysis",
            "summary": "",
            "url": "classes/App-Models-AIResult.html#method_codeAnalysis"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-AIResult.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-AIResult.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-AIResult.html#property_casts"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis",
            "name": "CodeAnalysis",
            "summary": "Code\u0020Analysis\u0020Model.",
            "url": "classes/App-Models-CodeAnalysis.html"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis\u003A\u003AaiResults\u0028\u0029",
            "name": "aiResults",
            "summary": "",
            "url": "classes/App-Models-CodeAnalysis.html#method_aiResults"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-CodeAnalysis.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-CodeAnalysis.html#property_casts"
        },                {
            "fqsen": "\\App\\Models\\ParsedItem",
            "name": "ParsedItem",
            "summary": "Parsed\u0020Item\u0020Model.",
            "url": "classes/App-Models-ParsedItem.html"
        },                {
            "fqsen": "\\App\\Models\\ParsedItem\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-ParsedItem.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\ParsedItem\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-ParsedItem.html#property_casts"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "User\u0020Model.",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService",
            "name": "CodeAnalysisService",
            "summary": "Code\u0020Analysis\u0020Service.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020CodeAnalysisService.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AgetParserService\u0028\u0029",
            "name": "getParserService",
            "summary": "Retrieve\u0020the\u0020ParserService\u0020instance.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_getParserService"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AanalyzeFile\u0028\u0029",
            "name": "analyzeFile",
            "summary": "Create\u0020or\u0020retrieve\u0020a\u0020CodeAnalysis\u0020record\u0020for\u0020a\u0020given\u0020file.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_analyzeFile"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AbuildAstSummary\u0028\u0029",
            "name": "buildAstSummary",
            "summary": "Generate\u0020a\u0020summary\u0020of\u0020the\u0020AST\u0020by\u0020visiting\u0020its\u0020nodes.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_buildAstSummary"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003ArunAnalysis\u0028\u0029",
            "name": "runAnalysis",
            "summary": "Queue\u0020missing\u0020AI\u0020analysis\u0020passes\u0020for\u0020a\u0020CodeAnalysis\u0020record.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_runAnalysis"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AbuildPromptForPass\u0028\u0029",
            "name": "buildPromptForPass",
            "summary": "Construct\u0020the\u0020prompt\u0020text\u0020for\u0020a\u0020specific\u0020AI\u0020analysis\u0020pass.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_buildPromptForPass"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AgetRawCode\u0028\u0029",
            "name": "getRawCode",
            "summary": "Retrieve\u0020the\u0020raw\u0020PHP\u0020code\u0020from\u0020a\u0020given\u0020file\u0020path.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_getRawCode"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003A\u0024openAIService",
            "name": "openAIService",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#property_openAIService"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003A\u0024parserService",
            "name": "parserService",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#property_parserService"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService",
            "name": "OpenAIService",
            "summary": "OpenAI\u0020Service.",
            "url": "classes/App-Services-AI-OpenAIService.html"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService\u003A\u003AgetLastUsage\u0028\u0029",
            "name": "getLastUsage",
            "summary": "Retrieve\u0020the\u0020usage\u0020data\u0020from\u0020the\u0020last\u0020OpenAI\u0020API\u0020request.",
            "url": "classes/App-Services-AI-OpenAIService.html#method_getLastUsage"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService\u003A\u003AperformOperation\u0028\u0029",
            "name": "performOperation",
            "summary": "Execute\u0020a\u0020specified\u0020AI\u0020operation\u0020using\u0020OpenAI\u0027s\u0020API.",
            "url": "classes/App-Services-AI-OpenAIService.html#method_performOperation"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService\u003A\u003A\u0024lastUsage",
            "name": "lastUsage",
            "summary": "",
            "url": "classes/App-Services-AI-OpenAIService.html#property_lastUsage"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\DocblockParser",
            "name": "DocblockParser",
            "summary": "DocBlock\u0020Parser.",
            "url": "classes/App-Services-Parsing-DocblockParser.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\DocblockParser\u003A\u003AparseDocblock\u0028\u0029",
            "name": "parseDocblock",
            "summary": "Parse\u0020a\u0020DocBlock\u0020to\u0020extract\u0020summary,\u0020description,\u0020and\u0020annotations.",
            "url": "classes/App-Services-Parsing-DocblockParser.html#method_parseDocblock"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService",
            "name": "ParserService",
            "summary": "Parser\u0020Service.",
            "url": "classes/App-Services-Parsing-ParserService.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService\u003A\u003AcollectPhpFiles\u0028\u0029",
            "name": "collectPhpFiles",
            "summary": "Collect\u0020all\u0020PHP\u0020files\u0020based\u0020on\u0020configuration\u0020settings.",
            "url": "classes/App-Services-Parsing-ParserService.html#method_collectPhpFiles"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "Parse\u0020a\u0020single\u0020PHP\u0020file\u0020into\u0020its\u0020Abstract\u0020Syntax\u0020Tree\u0020\u0028AST\u0029.",
            "url": "classes/App-Services-Parsing-ParserService.html#method_parseFile"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService\u003A\u003AgetPhpFiles\u0028\u0029",
            "name": "getPhpFiles",
            "summary": "Recursively\u0020retrieve\u0020all\u0020PHP\u0020files\u0020within\u0020a\u0020specified\u0020directory.",
            "url": "classes/App-Services-Parsing-ParserService.html#method_getPhpFiles"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor",
            "name": "UnifiedAstVisitor",
            "summary": "Unified\u0020AST\u0020Visitor.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020UnifiedAstVisitor.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AsetCurrentFile\u0028\u0029",
            "name": "setCurrentFile",
            "summary": "Set\u0020the\u0020current\u0020file\u0020being\u0020parsed.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_setCurrentFile"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AenterNode\u0028\u0029",
            "name": "enterNode",
            "summary": "Called\u0020when\u0020entering\u0020a\u0020node\u0020in\u0020the\u0020AST.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_enterNode"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AleaveNode\u0028\u0029",
            "name": "leaveNode",
            "summary": "Called\u0020when\u0020leaving\u0020a\u0020node\u0020in\u0020the\u0020AST.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_leaveNode"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AgetItems\u0028\u0029",
            "name": "getItems",
            "summary": "Retrieve\u0020all\u0020collected\u0020parsed\u0020items.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_getItems"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AresolveClassLikeType\u0028\u0029",
            "name": "resolveClassLikeType",
            "summary": "Determine\u0020the\u0020type\u0020of\u0020a\u0020ClassLike\u0020node.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_resolveClassLikeType"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AcollectMethods\u0028\u0029",
            "name": "collectMethods",
            "summary": "Gather\u0020methods\u0020from\u0020a\u0020ClassLike\u0020node,\u0020extracting\u0020doc\u0020info\u0020\u0026\u0020parameters.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_collectMethods"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AcollectMethodParams\u0028\u0029",
            "name": "collectMethodParams",
            "summary": "Collect\u0020parameters\u0020from\u0020a\u0020class\u0020method.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_collectMethodParams"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AcollectFunctionParams\u0028\u0029",
            "name": "collectFunctionParams",
            "summary": "Collect\u0020parameters\u0020from\u0020a\u0020free\u002Dfloating\u0020function.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_collectFunctionParams"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AtypeToString\u0028\u0029",
            "name": "typeToString",
            "summary": "Convert\u0020a\u0020PhpParser\u0020type\u0020node\u0020into\u0020a\u0020string\u0020representation.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_typeToString"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AextractDocInfo\u0028\u0029",
            "name": "extractDocInfo",
            "summary": "Extract\u0020docblock\u0020info\u0020\u0028short\u0020description\u0020\u002B\u0020annotations\u0029\u0020from\u0020a\u0020node.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_extractDocInfo"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#property_items"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A\u0024currentFile",
            "name": "currentFile",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#property_currentFile"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A\u0024currentNamespace",
            "name": "currentNamespace",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#property_currentNamespace"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/app-console-commands.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db",
            "name": "Db",
            "summary": "",
            "url": "namespaces/app-console-commands-db.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Experimental",
            "name": "Experimental",
            "summary": "",
            "url": "namespaces/app-console-commands-experimental.html"
        },                {
            "fqsen": "\\App\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/app-facades.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Jobs",
            "name": "Jobs",
            "summary": "",
            "url": "namespaces/app-jobs.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\App\\Services\\AI",
            "name": "AI",
            "summary": "",
            "url": "namespaces/app-services-ai.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing",
            "name": "Parsing",
            "summary": "",
            "url": "namespaces/app-services-parsing.html"
        }            ]
);
