Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand",
            "name": "AnalyzeFilesCommand",
            "summary": "Example\u0020command\u0020to\u0020parse\u0020files,\u0020store\u0020them\u0020in\u0020code_analyses,\nthen\u0020run\u0020multi\u002Dpass\u0020AI,\u0020storing\u0020each\u0020pass\u0020in\u0020ai_results.",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003AexecuteCommand\u0028\u0029",
            "name": "executeCommand",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#method_executeCommand"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003AexportToJson\u0028\u0029",
            "name": "exportToJson",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#method_exportToJson"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\AnalyzeFilesCommand\u003A\u003A\u0024analysisService",
            "name": "analysisService",
            "summary": "",
            "url": "classes/App-Console-Commands-AnalyzeFilesCommand.html#property_analysisService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand",
            "name": "DbBackupCommand",
            "summary": "",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbBackupCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-Db-DbBackupCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand",
            "name": "DbRestoreCommand",
            "summary": "",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003AnormalizePath\u0028\u0029",
            "name": "normalizePath",
            "summary": "Normalize\u0020a\u0020given\u0020path\u0020to\u0020its\u0020absolute\u0020form.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#method_normalizePath"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db\\DbRestoreCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-Db-DbRestoreCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand",
            "name": "FilesCommand",
            "summary": "FilesCommand\n\u0020\u002D\u0020Provides\u0020shared\u0020options\u003A\u0020\u002D\u002Doutput\u002Dfile,\u0020\u002D\u002Dlimit\u002Dclass,\u0020\u002D\u002Dlimit\u002Dmethod\n\u0020\u002D\u0020Many\u0020commands\u0020can\u0020extend\u0020this\u0020for\u0020consistent\u0020option\u0020handling",
            "url": "classes/App-Console-Commands-FilesCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AexecuteCommand\u0028\u0029",
            "name": "executeCommand",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_executeCommand"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AgetOutputFile\u0028\u0029",
            "name": "getOutputFile",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_getOutputFile"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AgetClassLimit\u0028\u0029",
            "name": "getClassLimit",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_getClassLimit"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003AgetMethodLimit\u0028\u0029",
            "name": "getMethodLimit",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#method_getMethodLimit"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FilesCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Console-Commands-FilesCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand",
            "name": "ParseFilesCommand",
            "summary": "Example\u0020command\u0020that\u0020parses\u0020PHP\u0020files\u0020\u0028including\u0020traits\u0029.",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003AexportJson\u0028\u0029",
            "name": "exportJson",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method_exportJson"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003AdisplayTable\u0028\u0029",
            "name": "displayTable",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#method_displayTable"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ParseFilesCommand\u003A\u003A\u0024parserService",
            "name": "parserService",
            "summary": "",
            "url": "classes/App-Console-Commands-ParseFilesCommand.html#property_parserService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand",
            "name": "PassesProcessCommand",
            "summary": "Class\u0020PassesProcessCommand",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\PassesProcessCommand\u003A\u003A\u0024analysisService",
            "name": "analysisService",
            "summary": "",
            "url": "classes/App-Console-Commands-PassesProcessCommand.html#property_analysisService"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob",
            "name": "ProcessAnalysisPassJob",
            "summary": "ProcessAnalysisPassJob.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020ProcessAnalysisPassJob.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#property_description"
        },                {
            "fqsen": "\\App\\Console\\Commands\\ProcessAnalysisPassJob\u003A\u003A\u0024analysisService",
            "name": "analysisService",
            "summary": "",
            "url": "classes/App-Console-Commands-ProcessAnalysisPassJob.html#property_analysisService"
        },                {
            "fqsen": "\\App\\Facades\\OpenAI",
            "name": "OpenAI",
            "summary": "",
            "url": "classes/App-Facades-OpenAI.html"
        },                {
            "fqsen": "\\App\\Facades\\OpenAI\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "",
            "url": "classes/App-Facades-OpenAI.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController",
            "name": "AnalysisController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnalysisController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020all\u0020CodeAnalysis\u0020records.",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Show\u0020details\u0020\u0028including\u0020AI\u0020results\u0029\u0020for\u0020a\u0020single\u0020CodeAnalysis\u0020record.",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003Aanalyze\u0028\u0029",
            "name": "analyze",
            "summary": "Trigger\u0020the\u0020parse\u0020\u002B\u0020queued\u0020AI\u0020passes\u0020for\u0020a\u0020single\u0020file\u0020or\u0020folder\u0020path.",
            "url": "classes/App-Http-Controllers-AnalysisController.html#method_analyze"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnalysisController\u003A\u003A\u0024codeAnalysisService",
            "name": "codeAnalysisService",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnalysisController.html#property_codeAnalysisService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob",
            "name": "ProcessAnalysisPassJob",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#method___construct"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "The\u0020job\u0020handle\u0020method.\u0020This\u0020is\u0020where\u0020the\u0020AI\u0020pass\u0020is\u0020executed.",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#method_handle"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A\u0024codeAnalysisId",
            "name": "codeAnalysisId",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#property_codeAnalysisId"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A\u0024passName",
            "name": "passName",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#property_passName"
        },                {
            "fqsen": "\\App\\Jobs\\ProcessAnalysisPassJob\u003A\u003A\u0024dryRun",
            "name": "dryRun",
            "summary": "",
            "url": "classes/App-Jobs-ProcessAnalysisPassJob.html#property_dryRun"
        },                {
            "fqsen": "\\App\\Models\\AIResult",
            "name": "AIResult",
            "summary": "",
            "url": "classes/App-Models-AIResult.html"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003AcodeAnalysis\u0028\u0029",
            "name": "codeAnalysis",
            "summary": "",
            "url": "classes/App-Models-AIResult.html#method_codeAnalysis"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "",
            "url": "classes/App-Models-AIResult.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-AIResult.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\AIResult\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-AIResult.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis",
            "name": "CodeAnalysis",
            "summary": "",
            "url": "classes/App-Models-CodeAnalysis.html"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis\u003A\u003AaiResults\u0028\u0029",
            "name": "aiResults",
            "summary": "",
            "url": "classes/App-Models-CodeAnalysis.html#method_aiResults"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "",
            "url": "classes/App-Models-CodeAnalysis.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\CodeAnalysis\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-CodeAnalysis.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\ParsedItem",
            "name": "ParsedItem",
            "summary": "",
            "url": "classes/App-Models-ParsedItem.html"
        },                {
            "fqsen": "\\App\\Models\\ParsedItem\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "",
            "url": "classes/App-Models-ParsedItem.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\ParsedItem\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-ParsedItem.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "Get\u0020the\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService",
            "name": "CodeAnalysisService",
            "summary": "Manages\u0020AST\u0020parsing\u0020\u002B\u0020multi\u002Dpass\u0020AI\u0020for\u0020code\u0020analysis\u0020in\u0020an\u0020async\u0020manner.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AgetParserService\u0028\u0029",
            "name": "getParserService",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_getParserService"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AanalyzeFile\u0028\u0029",
            "name": "analyzeFile",
            "summary": "Create\u0020or\u0020reuse\u0020a\u0020CodeAnalysis\u0020for\u0020the\u0020specified\u0020file.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_analyzeFile"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AbuildAstSummary\u0028\u0029",
            "name": "buildAstSummary",
            "summary": "Summarize\u0020AST\u0020by\u0020scanning\u0020it\u0020with\u0020UnifiedAstVisitor.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_buildAstSummary"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003ArunAnalysis\u0028\u0029",
            "name": "runAnalysis",
            "summary": "Instead\u0020of\u0020synchronous\u0020calls,\u0020we\u0020now\u0020queue\u0020each\u0020missing\u0020pass.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_runAnalysis"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AbuildPromptForPass\u0028\u0029",
            "name": "buildPromptForPass",
            "summary": "Build\u0020a\u0020prompt\u0020for\u0020a\u0020specific\u0020pass\u0020\u0028used\u0020by\u0020ProcessAnalysisPassJob\u0029.",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_buildPromptForPass"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003AgetRawCode\u0028\u0029",
            "name": "getRawCode",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#method_getRawCode"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003A\u0024openAIService",
            "name": "openAIService",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#property_openAIService"
        },                {
            "fqsen": "\\App\\Services\\AI\\CodeAnalysisService\u003A\u003A\u0024parserService",
            "name": "parserService",
            "summary": "",
            "url": "classes/App-Services-AI-CodeAnalysisService.html#property_parserService"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService",
            "name": "OpenAIService",
            "summary": "Handles\u0020calls\u0020to\u0020the\u0020OpenAI\u0020API\u0020via\u0020chat\u0028\u0029\u0020endpoints,\ncapturing\u0020token\u0020usage\u0020in\u0020\u0024this\u002D\u003ElastUsage.",
            "url": "classes/App-Services-AI-OpenAIService.html"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService\u003A\u003AgetLastUsage\u0028\u0029",
            "name": "getLastUsage",
            "summary": "",
            "url": "classes/App-Services-AI-OpenAIService.html#method_getLastUsage"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService\u003A\u003AperformOperation\u0028\u0029",
            "name": "performOperation",
            "summary": "",
            "url": "classes/App-Services-AI-OpenAIService.html#method_performOperation"
        },                {
            "fqsen": "\\App\\Services\\AI\\OpenAIService\u003A\u003A\u0024lastUsage",
            "name": "lastUsage",
            "summary": "",
            "url": "classes/App-Services-AI-OpenAIService.html#property_lastUsage"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\DocblockParser",
            "name": "DocblockParser",
            "summary": "DocblockParser",
            "url": "classes/App-Services-Parsing-DocblockParser.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\DocblockParser\u003A\u003AparseDocblock\u0028\u0029",
            "name": "parseDocblock",
            "summary": "",
            "url": "classes/App-Services-Parsing-DocblockParser.html#method_parseDocblock"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService",
            "name": "ParserService",
            "summary": "Provides\u0020file\u0020collection\u0020and\u0020single\u002Dvisitor\u0020parsing.",
            "url": "classes/App-Services-Parsing-ParserService.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService\u003A\u003AcollectPhpFiles\u0028\u0029",
            "name": "collectPhpFiles",
            "summary": "Collect\u0020.php\u0020files\u0020from\u0020config\u0028\u0027parsing.files\u0027\u0029\u0020\u002B\u0020config\u0028\u0027parsing.folders\u0027\u0029",
            "url": "classes/App-Services-Parsing-ParserService.html#method_collectPhpFiles"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "Parse\u0020a\u0020single\u0020PHP\u0020file\u0020with\u0020optional\u0020visitors,\u0020and\u0020return\u0020the\u0020raw\u0020AST\u0020array.",
            "url": "classes/App-Services-Parsing-ParserService.html#method_parseFile"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\ParserService\u003A\u003AgetPhpFiles\u0028\u0029",
            "name": "getPhpFiles",
            "summary": "Recursively\u0020get\u0020.php\u0020files\u0020from\u0020a\u0020directory.",
            "url": "classes/App-Services-Parsing-ParserService.html#method_getPhpFiles"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor",
            "name": "UnifiedAstVisitor",
            "summary": "Single\u002Dpass\u0020visitor\u0020collecting\u0020classes\u0020\u0028traits,\u0020interfaces\u0029\u0020and\u0020free\u002Dfloating\u0020functions.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AsetCurrentFile\u0028\u0029",
            "name": "setCurrentFile",
            "summary": "Set\u0020the\u0020current\u0020file\u0020being\u0020parsed\u003B\u0020used\u0020for\u0020referencing\u0020in\u0020output.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_setCurrentFile"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AenterNode\u0028\u0029",
            "name": "enterNode",
            "summary": "Called\u0020when\u0020entering\u0020a\u0020node\u0020in\u0020the\u0020AST.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_enterNode"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AleaveNode\u0028\u0029",
            "name": "leaveNode",
            "summary": "Called\u0020when\u0020leaving\u0020a\u0020node.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_leaveNode"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AgetItems\u0028\u0029",
            "name": "getItems",
            "summary": "Returns\u0020an\u0020array\u0020of\u0020all\u0020collected\u0020items\u0020\u0028classes,\u0020traits,\u0020interfaces,\u0020functions\u0029.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_getItems"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AresolveClassLikeType\u0028\u0029",
            "name": "resolveClassLikeType",
            "summary": "Distinguish\u0020if\u0020a\u0020node\u0020is\u0020a\u0020Class,\u0020Trait,\u0020or\u0020Interface.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_resolveClassLikeType"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AcollectMethods\u0028\u0029",
            "name": "collectMethods",
            "summary": "Gather\u0020methods\u0020from\u0020a\u0020ClassLike\u0020node,\u0020extracting\u0020doc\u0020info\u0020\u0026\u0020parameters.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_collectMethods"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AcollectMethodParams\u0028\u0029",
            "name": "collectMethodParams",
            "summary": "Collect\u0020parameters\u0020from\u0020a\u0020class\u0020method.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_collectMethodParams"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AcollectFunctionParams\u0028\u0029",
            "name": "collectFunctionParams",
            "summary": "Collect\u0020parameters\u0020from\u0020a\u0020free\u002Dfloating\u0020function.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_collectFunctionParams"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AtypeToString\u0028\u0029",
            "name": "typeToString",
            "summary": "Convert\u0020a\u0020PhpParser\u0020type\u0020node\u0020into\u0020a\u0020string\u0020representation.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_typeToString"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003AextractDocInfo\u0028\u0029",
            "name": "extractDocInfo",
            "summary": "Extract\u0020docblock\u0020info\u0020\u0028short\u0020description\u0020\u002B\u0020annotations\u0029\u0020from\u0020a\u0020node.",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#method_extractDocInfo"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#property_items"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A\u0024currentFile",
            "name": "currentFile",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#property_currentFile"
        },                {
            "fqsen": "\\App\\Services\\Parsing\\UnifiedAstVisitor\u003A\u003A\u0024currentNamespace",
            "name": "currentNamespace",
            "summary": "",
            "url": "classes/App-Services-Parsing-UnifiedAstVisitor.html#property_currentNamespace"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/app-console-commands.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\Db",
            "name": "Db",
            "summary": "",
            "url": "namespaces/app-console-commands-db.html"
        },                {
            "fqsen": "\\App\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/app-facades.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Jobs",
            "name": "Jobs",
            "summary": "",
            "url": "namespaces/app-jobs.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\App\\Services\\AI",
            "name": "AI",
            "summary": "",
            "url": "namespaces/app-services-ai.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        },                {
            "fqsen": "\\App\\Services\\Parsing",
            "name": "Parsing",
            "summary": "",
            "url": "namespaces/app-services-parsing.html"
        }            ]
);
